In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('student-mat.csv')
data.head(5)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [4]:
data.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [5]:
df = data[["G1","G2","studytime","failures","absences"]]
X = np.array(df)
Y = np.array(data[["G3"]])

In [6]:
X

array([[ 5,  6,  2,  0,  6],
       [ 5,  5,  2,  0,  4],
       [ 7,  8,  2,  3, 10],
       ...,
       [10,  8,  1,  3,  3],
       [11, 12,  1,  0,  0],
       [ 8,  9,  1,  0,  5]], dtype=int64)

In [7]:
Y

array([[ 6],
       [ 6],
       [10],
       [15],
       [10],
       [15],
       [11],
       [ 6],
       [19],
       [15],
       [ 9],
       [12],
       [14],
       [11],
       [16],
       [14],
       [14],
       [10],
       [ 5],
       [10],
       [15],
       [15],
       [16],
       [12],
       [ 8],
       [ 8],
       [11],
       [15],
       [11],
       [11],
       [12],
       [17],
       [16],
       [12],
       [15],
       [ 6],
       [18],
       [15],
       [11],
       [13],
       [11],
       [12],
       [18],
       [11],
       [ 9],
       [ 6],
       [11],
       [20],
       [14],
       [ 7],
       [13],
       [13],
       [10],
       [11],
       [13],
       [10],
       [15],
       [15],
       [ 9],
       [16],
       [11],
       [11],
       [ 9],
       [ 9],
       [10],
       [15],
       [12],
       [ 6],
       [ 8],
       [16],
       [15],
       [10],
       [ 5],
       [14],
       [11],
       [10],
       [10],

In [8]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.2,random_state=1)

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain,ytrain)

LinearRegression()

In [11]:
regressor.score(xtrain,ytrain)

0.8330842539438935

In [12]:
pred = regressor.predict(xtest)
pred

array([[ 5.20672723],
       [10.04649373],
       [ 6.87899815],
       [ 8.78933981],
       [ 9.83460413],
       [11.27126926],
       [ 7.64854358],
       [12.4146178 ],
       [11.82872281],
       [ 7.0920329 ],
       [12.43523448],
       [14.6370162 ],
       [ 6.16499328],
       [ 7.39079901],
       [ 8.30540116],
       [10.96675449],
       [15.500217  ],
       [16.23718176],
       [ 5.89361318],
       [ 9.54947355],
       [11.15802741],
       [18.56775183],
       [ 9.26932581],
       [11.94120837],
       [15.46209948],
       [ 4.38220068],
       [11.0992932 ],
       [ 8.01924038],
       [ 8.92290872],
       [13.06546914],
       [12.13834219],
       [11.7574706 ],
       [ 6.76152974],
       [11.01795354],
       [13.35848931],
       [ 7.7372161 ],
       [10.442146  ],
       [ 8.44284219],
       [ 7.14108151],
       [10.68660675],
       [ 9.376265  ],
       [10.57966757],
       [16.48419481],
       [ 6.4101298 ],
       [ 9.89589064],
       [11